version: "3.3"
services:
    mysql:
        image: mysql
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: "carlos123"
        volumes:
            - ${PWD}
        networks: 
            - my_network
    
    php:
        image: php:8.0.5-fpm-alpine
        restart: always
        build:
            context: ./php
            dockerfile: dockerfile
        container_name: php
        working_dir: /var/www/html
        ports:
            - '9000:9000'
        volumes:
            - './app:/var/www/html'
        depends_on:
            - mysql
        networks: 
            - my_network
    
    nginx:
        image: nginx:stable-alpine
        container_name: nginx
        restart: always
        build:
            context: ./nginx
            dockerfile: dockerfile
        ports:
            - "8080:80"
            - "443:443"
            - "8000:8000"
            - "3000"
        expose: 
            - '8000'
            - '443'
        links:
            - php
        depends_on: 
            - php
        volumes:
            - './app:/var/www/html'
            - './logs/nginx:/var/log/nginx'
            - './config/nginx:/etc/nginx/conf.d'
            - './config/nginx/sites-available:/etc/nginx/sites-available'
            - './config/nginx/sites-enabled:/etc/nginx/sites-enabled'
        networks: 
            - my_network
    
networks:
    my_network:
        driver: bridge
