version: "3.3"
services:
    mysql:
        image: mysql
        container_name: mysql
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: "carlos123"
        volumes:
            - ${PWD}
        networks: 
            - my_network
        ports: 
            - '3306:3306'
    php:
        # url: https://hub.docker.com/r/trafex/php-nginx/
        container_name: php
        build:
            context: ./nginx
            dockerfile: dockerfile 
        ports:
            - '8080:8080'
            - '443:8443'
        depends_on:
            - mysql
        volumes:
            - './app:/var/www/html'
            - './logs/nginx:/var/log/nginx'
            - './config/nginx:/etc/nginx/conf.d'
            - './config/nginx/sites-available:/etc/nginx/sites-available'
            - './config/nginx/sites-enabled:/etc/nginx/sites-enabled'
            - './config/php/php.ini:/etc/php8/php.ini'
        networks: 
            - my_network
        links:
            - mysql
    
networks:
    my_network:
        driver: bridge
