FROM trafex/php-nginx:latest

ENV PHPIZE_DEPS \
    git \
    file \
    re2c \
    autoconf \
    make \
    zlib \
    zlib-dev \
    g++

# Install composer from the official image
COPY --from=composer /usr/bin/composer /usr/bin/composer

EXPOSE 8080 443

USER root
RUN apk add sudo
RUN apk update && apk upgrade
RUN apk add php8-common
RUN apk add php8-pdo_mysql
RUN apk add php8-iconv
RUN apk add php8-tokenizer
RUN apk add php8-simplexml
RUN apk add php8-posix
RUN apk add --no-cache --virtual .build-deps $PHPIZE_DEPS
RUN apk --no-cache add php8-pear php8-dev gcc musl-dev make
RUN apk add php8-pecl-xdebug
RUN apk add git

# XDEBUG
# RUN apk add --no-cache --virtual .build-deps $PHPIZE_DEPS \
#     && pecl install xdebug-3.0.0 \
#     && docker-php-ext-enable xdebug \
#     && apk del -f .build-deps

# RUN /usr/symfony-installer new --full estudo_symfony

USER nobody

# Run composer install to install the dependencies
# RUN composer install --optimize-autoloader --no-interaction --no-progress

